version: '3'
services:
  web:
    image: nginx:latest
    volumes:
    - .:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "9080:80"
    links:
    - php
  php:
    build: .
    volumes:
    - .:/code
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
