name: Publish
on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      # The name of your gem/package.
      PACKAGE_NAME: "eduframe-php-client"

    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: php
        package-name: ${{ env.PACKAGE_NAME }}
        version-file: "composer.json"
